server:
  port: 8080

spring:
  application:
    name: api-gateway

jwt:
  secret: my-super-secret-key-my-super-secret-key

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: voter-service
          uri: lb://VOTER-MANAGEMENT-SERVICE
          predicates:
            - Path=/voters/**
          filters:
            - name: JwtAuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
