spring.application.name=api-gateway

server.port=8080

# connect to Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# to see routes in actuator
management.endpoint.gateway.access=read-only
management.endpoints.web.exposure.include=gateway

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
